# Generated by Django 5.2.8 on 2026-02-07 22:21

import django.db.models.deletion
from django.db import migrations, models

import api.utils


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=api.utils.UserContentUploadPath("skills"),
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата загрузки"),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="skills.skill",
                        verbose_name="Навык",
                    ),
                ),
            ],
        ),
    ]
