# Generated by Django 5.2.8 on 2026-02-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0002_skillimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name="Описание"),
        ),
    ]
