# Generated by Django 5.2.8 on 2026-02-08 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import skills.utils


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0003_skill_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillimage",
            name="image",
            field=models.ImageField(
                upload_to=skills.utils.skill_image_upload_path,
                verbose_name="Изображение",
            ),
        ),
        migrations.CreateModel(
            name="WantsToLearn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wants_to_learn",
                        to="skills.subcategory",
                        verbose_name="Подкатегория",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wants_to_learn",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Хочет научиться",
                "verbose_name_plural": "Хотят научиться",
                "unique_together": {("user", "subcategory")},
            },
        ),
    ]
