# Generated by Django 5.2.8 on 2026-02-08 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0004_alter_skillimage_image_wantstolearn"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillExchangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает рассмотрения"),
                            ("accepted", "Принята"),
                            ("rejected", "Отклонена"),
                            ("cancelled", "Отменена инициатором"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата ответа"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_requests_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель предложения",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Инициатор обмена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на обмен навыками",
                "verbose_name_plural": "Заявки на обмен навыками",
                "ordering": ["-created_at"],
                "unique_together": {("requester", "recipient")},
            },
        ),
    ]
