# Generated by Django 5.2.8 on 2026-02-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0007_skillexchangenotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(
                default="#42CAD1",
                max_length=50,
                unique=True,
                verbose_name="Цвет категории",
            ),
        ),
    ]
