# Generated by Django 5.2.8 on 2026-02-07 22:21

from django.db import migrations, models

import api.utils


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="О себе"),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api.utils.UserContentUploadPath("avatar"),
                verbose_name="Аватар",
            ),
        ),
    ]
