# Generated by Django 5.2.8 on 2026-02-08 18:30

from django.db import migrations, models

import users.utils


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_about_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.utils.user_avatar_upload_path,
                verbose_name="Аватар",
            ),
        ),
    ]
